apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rhtap-demo2-gitops
  description: This is GitOps manifest for rhtap-demo2   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: rhtap-demo2
    janus-idp.io/tekton: rhtap-demo2 
    backstage.io/kubernetes-id: rhtap-demo2 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:rhtap-demo2
